# Generated by Django 3.2.7 on 2021-10-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicals',
            name='arrive_date',
            field=models.DateField(default='2022/03/05'),
        ),
        migrations.AlterField(
            model_name='chemicals',
            name='expire_date',
            field=models.DateField(default='2022/03/05'),
        ),
    ]
