# Generated by Django 3.2.7 on 2021-11-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0004_auto_20211022_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicals',
            name='CAT',
            field=models.CharField(default='ABCD', max_length=20),
        ),
        migrations.AddField(
            model_name='chemicals',
            name='LOT',
            field=models.CharField(default='ABCD', max_length=20),
        ),
        migrations.AddField(
            model_name='chemicals',
            name='temperature',
            field=models.CharField(choices=[('RT', 'RT'), ('4', '4'), ('-20', '-20')], default='RT', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
