# Generated by Django 3.2.7 on 2021-11-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0005_auto_20211105_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicals',
            name='operator',
            field=models.CharField(default='ABCD', max_length=20),
        ),
    ]
